# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HalfDay' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'JRDB'
pod 'HandyJSON'
pod 'SnapKit'

  # Pods for HalfDay

  target 'HalfDayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HalfDayUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
